import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/layouts/Nav";
import Sidebar from "@/layouts/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div>
            <Sidebar />
          </div>
          <div className="flex-1 pl-72 overflow-x-hidden p-0 m-0">
            <Nav />
            <div className="mt-3 ml-4">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
